inherit_gem:
  rubocul: rubocul_default.yml

AllCops:
  TargetRubyVersion: 3.3.5  # Update to your version of ruby
  TargetRailsVersion: 7.2.1 # Update to your version of rails

Metrics/BlockLength:
  Exclude:
    - 'config/environments/development.rb' # file generated during 'rails new'

RSpec/BeforeAfterAll:
  Exclude:
    - spec/sword/mets/mets_file_spec.rb
    - spec/sword/mets/proquest_mets_file_spec.rb
    - spec/sword/mets/xml_data_element_spec.rb
    - spec/sword/mets/proquest_etd_xml_data_element_spec.rb
    - spec/sword/mets/eprints_dc_xml_data_element_spec.rb
    - spec/sword/mets/mods_xml_data_element_spec.rb

RSpec/InstanceVariable:
  Exclude:
    - spec/sword/mets/mets_file_spec.rb
    - spec/sword/mets/proquest_mets_file_spec.rb
    - spec/sword/mets/xml_data_element_spec.rb
    - spec/sword/mets/proquest_etd_xml_data_element_spec.rb
    - spec/sword/mets/eprints_dc_xml_data_element_spec.rb
    - spec/sword/mets/mods_xml_data_element_spec.rb
