inherit_gem:
  rubocul: rubocul_default.yml

AllCops:
  TargetRubyVersion: 3.3.5  # Update to your version of ruby
  TargetRailsVersion: 7.2.1 # Update to your version of rails

Metrics/BlockLength:
  Exclude:
    - 'config/environments/development.rb' # file generated durgin 'rails new'